<a href="https://colab.research.google.com/github/sankeerthana2511/sankeerthana/blob/main/700757550_ICP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Create a class Employee and then do the following:

• Create a data member to count the number of Employees

• Create a constructor to initialize name, family, salary, department

• Create a function to average salary

• Create a Fulltime Employee class and it should inherit the properties of Employee class

• Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [1]:
class Employee:
    employee_count = 0  # Data member to count the number of Employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.employee_count

class FulltimeEmployee(Employee):
    # Inheriting properties from the Employee class
    pass

# Creating instances of Employee class
employee1 = Employee("Sai Ram", "Uppalapati", 100000, "Manager")
employee2 = Employee("Rahul", "Chalamalasetti", 150000, "IT")

# Creating instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("Madhavi", "Cheerala", 75000, "Finance")
fulltime_employee2 = FulltimeEmployee("Shivathmika", "Vadluri", 60000, "Manager")

# Calling member functions
total_salary_employees = employee1.salary + employee2.salary
average_salary_employees = employee1.average_salary(total_salary_employees)

total_salary_fulltime_employees = fulltime_employee1.salary + fulltime_employee2.salary
average_salary_fulltime_employees = fulltime_employee1.average_salary(total_salary_fulltime_employees)

# Displaying results
print("Average Salary for Employees:", average_salary_employees)
print("Average Salary for Fulltime Employees:", average_salary_fulltime_employees)

Average Salary for Employees: 62500.0
Average Salary for Fulltime Employees: 33750.0


2.Numpy

Using NumPy create random vector of size 20 having only float in the range 1-20.

Then reshape the array to 4 by 5

Then replace the max in each row by 0 (axis=1)

In [2]:
# Import the NumPy library and alias it as 'np' for brevity and convention.
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

print("Original Random Vector:\n", random_vector)

Original Random Vector:
 [16.93641593 17.36272567  1.59440088 10.64804702 15.54873447  6.6072624
  6.72871566 14.14779362 12.78462341 11.35025893 16.69511468 17.35857361
 12.44354836  7.26292872 11.71720979 11.2755926   1.33190035 16.42840856
  3.42432896  5.13441193]


In [3]:
# Reshape the array to 4 by 5 (4 rows and 5 columns)
reshaped_array = random_vector.reshape(4, 5)

print(reshaped_array)

[[16.93641593 17.36272567  1.59440088 10.64804702 15.54873447]
 [ 6.6072624   6.72871566 14.14779362 12.78462341 11.35025893]
 [16.69511468 17.35857361 12.44354836  7.26292872 11.71720979]
 [11.2755926   1.33190035 16.42840856  3.42432896  5.13441193]]


In [4]:
# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[16.93641593  0.          1.59440088 10.64804702 15.54873447]
 [ 6.6072624   6.72871566  0.         12.78462341 11.35025893]
 [16.69511468  0.         12.44354836  7.26292872 11.71720979]
 [11.2755926   1.33190035  0.          3.42432896  5.13441193]]
